language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t ldcamachoc/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true ldcamachoc/react-test npm test

after_success:
  - docker image build -t ldcamachoc/multi-client ./client
  - docker image build -t ldcamachoc/multi-nginx ./nginx
  - docker image build -t ldcamachoc/multi-server ./server
  - docker image build -t ldcamachoc/multi-worker ./worker
  # Log into the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push ldcamachoc/multi-client
  - docker push ldcamachoc/multi-nginx
  - docker push ldcamachoc/multi-server
  - docker push ldcamachoc/multi-worker

deploy:
  provider: elasticbeanstalk
  region: us-east-1
  app: multidocker
  env: Multidocker-env
  bucket_name: elasticbeanstalk-us-east-1-189137563013
  bucker_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
