language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t ldcamachoc/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true ldcamachoc/react-test npm test

after_success:
  - docker image build -t ldcamachoc/multi-client ./client
  - docker image build -t ldcamachoc/multi-nginx ./nginx
  - docker image build -t ldcamachoc/multi-server ./server
  - docker image build -t ldcamachoc/multi-worker ./worker
  # Log into the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push ldcamachoc/multi-client
  - docker push ldcamachoc/multi-nginx
  - docker push ldcamachoc/multi-server
  - docker push ldcamachoc/multi-worker